/**
 * Post-build step: give every real page its own file on disk.
 *
 * Dealo is a single-page app — the bundle ships one index.html and React
 * Router swaps the page contents client-side. That works fine once you're on
 * the site, but the host only has that single file, so a direct request for
 * /privacy/ has no object to serve and comes back as HTTP 404. The page still
 * *renders* (the host returns index.html as its error body, and the router
 * takes over), but the status line says "not found", and that is what a
 * crawler or a link checker reads — which is why every URL in sitemap.xml was
 * being reported as a dead page even though a human could see it fine.
 *
 * Fix: after `vite build`, copy the built index.html to dist/<route>/index.html
 * for every crawlable route. Same app, same bundle — the only difference is
 * that the path now exists, so it answers with a genuine 200. Unknown paths
 * still 404, which is correct.
 *
 * ROUTES is also the single source for sitemap.xml (written here rather than
 * kept by hand in public/), so the sitemap can no longer list a URL that this
 * script hasn't produced a file for.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { BRAND_DEALS } from '../src/data/brandDeals.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.join(HERE, '..', 'dist');
const SITE_URL = 'https://getdealo.in';

// Trailing slashes on purpose: the host 301-redirects /privacy to /privacy/,
// so the slashed form is the URL that actually answers. Publishing the
// unslashed one would send every crawler and every shared link through a
// needless redirect hop first.
const ROUTES = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/how-it-works/', changefreq: 'monthly', priority: '0.8' },
  { path: '/brands/', changefreq: 'weekly', priority: '0.8' },
  ...BRAND_DEALS.map((b) => ({
    path: `/brands/${b.slug}/`,
    changefreq: 'weekly',
    priority: '0.7',
  })),
  { path: '/about/', changefreq: 'yearly', priority: '0.4' },
  { path: '/contact/', changefreq: 'yearly', priority: '0.4' },
  { path: '/privacy/', changefreq: 'yearly', priority: '0.2' },
  { path: '/terms/', changefreq: 'yearly', priority: '0.2' },
];

// Deliberately absent: /select and /results. They only mean anything with a
// live search behind them, so they stay out of the sitemap and out of the
// crawler's way (robots.txt disallows both).

const shell = await readFile(path.join(DIST, 'index.html'), 'utf8');

/**
 * Point the copy at its own address. Both tags exist in index.html hardcoded
 * to the homepage; usePageTitle rewrites them once React boots, but a crawler
 * that reads the raw file (and every link preview — WhatsApp, Slack, Twitter —
 * which never runs the JS at all) sees only what's in the file as served.
 */
function withCanonical(html, url) {
  return html
    .replace(
      /<link rel="canonical" href="[^"]*" \/>/,
      `<link rel="canonical" href="${url}" />`,
    )
    .replace(
      /<meta property="og:url" content="[^"]*" \/>/,
      `<meta property="og:url" content="${url}" />`,
    );
}

for (const route of ROUTES) {
  const url = `${SITE_URL}${route.path}`;
  const dir = path.join(DIST, route.path);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, 'index.html'), withCanonical(shell, url));
}

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/prerender.mjs on every build. Don't edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${ROUTES.map(
  (r) => `  <url>
    <loc>${SITE_URL}${r.path}</loc>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`,
).join('\n')}
</urlset>
`;
await writeFile(path.join(DIST, 'sitemap.xml'), sitemap);

console.log(`prerender: wrote ${ROUTES.length} pages + sitemap.xml`);
