"""What each voucher platform's checkout permits.

Read from `data/voucher_rules.json` (`_platform_rules`), which is generated by
`scripts/build_service_rules.py`. That file is the single source of truth for
platform behaviour, and this module exists so the pricing code never keeps its
own copy of it.

Why that matters: the same facts used to live twice, once in the data and once
as hand-typed constants in voucher_service. They disagreed, the code's copy won
silently, and a ₹29,999 Frido order was recommended as eight separate Maximize
purchases. Facts about a platform belong in the rulebook; only the reasoning
belongs in Python.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_RULES_PATH = Path(__file__).resolve().parents[2] / "data" / "voucher_rules.json"

# Used only if the rulebook is missing or unreadable — the most restrictive
# reading of every platform, so a broken file makes Dealo quiet rather than
# wrong.
_FALLBACK = {
    "gyftr": {"checkout_model": "multi_item", "vouchers_per_order": 1,
              "mixed_denominations": False, "requires_brand_stacking": True},
    "maximize": {"checkout_model": "single_item", "vouchers_per_order": 1,
                 "mixed_denominations": False, "requires_brand_stacking": True},
    "buyhatke": {"checkout_model": "single_item", "vouchers_per_order": 1,
                 "mixed_denominations": False, "requires_brand_stacking": False},
}


@lru_cache(maxsize=1)
def _all() -> dict:
    try:
        with _RULES_PATH.open() as f:
            rules = json.load(f).get("_platform_rules")
        return rules or _FALLBACK
    except (OSError, json.JSONDecodeError):
        return _FALLBACK


def rules_for(platform: str | None) -> dict:
    """The rulebook entry for a platform name, however it was capitalised."""
    return _all().get((platform or "gyftr").lower(), _FALLBACK["gyftr"])


def sells_one_item_per_checkout(platform: str | None) -> bool:
    """True where a checkout holds one line item, so a second amount means a
    second purchase. Gyftr has a real cart; the other two do not."""
    return rules_for(platform).get("checkout_model") == "single_item"


def allows_mixed_denominations(platform: str | None) -> bool:
    return bool(rules_for(platform).get("mixed_denominations"))


def max_vouchers_per_checkout(platform: str | None, brand_allows_stacking: bool | None) -> int | None:
    """How many vouchers of ONE denomination this checkout will sell at once.

    None means unlimited (Gyftr's cart). Otherwise a number.

    `brand_allows_stacking` is the brand's own `can_combine` answer, and it
    gates the platform's allowance wherever the rulebook says it should:
    buying four vouchers a shop will not accept on one bill is not a saving.
    None means the terms never said, which is treated as "no" — the more
    restrictive reading, per the standing rule that the stricter source wins.
    """
    rules = rules_for(platform)
    if rules.get("requires_brand_stacking") and not brand_allows_stacking:
        return 1
    per_order = rules.get("vouchers_per_order")
    if per_order == "unlimited":
        return None
    try:
        return max(1, int(per_order))
    except (TypeError, ValueError):
        return 1
